### ISSUE TITLE
The best way of tweaking constraints in an imported model

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#718] opened 2016-05-10 21:23 UTC
I would like to be able to do something like:
```python
from aircraft.wing import Wing

wi = Wing.standalone737()
# change a constraint (e.g. remove a variable from the constraint)
wi.localsolve()
```

What is the best way of doing this?

**Comment by bqpd** [comment] 2016-05-10 21:28
depends on what exactly you're doing! For your example:

option 1: `wi.subinplace(x, 0)`

option 2: `wi[0].left = wi[0].left - x`

**Comment by pgkirsch** [comment] 2016-05-10 21:43
To complicate things a little bit, when I tried option 1, it make a signomial constraint into a posynomial constraint (not by accident), so when I solve I get the following:

```python
/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in mono_approximation(self, x0)
    420     def mono_approximation(self, x0):
    421         raise TypeError("Monomial approximation of %s is unnecessary - "
--> 422                         "it's already a Monomial." % str(self))
    423 
    424 

TypeError: Monomial approximation of 39.5*AR**2*C_{L_{aw}}**-2 is unnecessary - it's already a Monomial.
```

**Comment by pgkirsch** [comment] 2016-05-10 21:44
And if I understand correctly, option 2 doesn't work when I only have varkeys at my disposal

**Comment by bqpd** [comment] 2016-05-10 21:54
1. hmm, the SignomialInequality should be able to handle that...
2. `wi[0].left = wi[0].left - wi["x"]` should work fine

**Comment by pgkirsch** [comment] 2016-05-11 04:52
```python
from gpkit.models.gpkitmodels.aircraft.wing import Wing
wi = Wing.standalone737()
wi.subinplace(wimod['M'], 0)
wi.localsolve()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-6eb6a7eb5069> in <module>()
----> 1 wi.localsolve()

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity-1)
---> 80             result = solvefn(solver, verbosity-1, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/signomial_program.pyc in localsolve(self, solver, verbosity, x0, rel_tol, iteration_limit, **kwargs)
    103     appear to be converging, you may wish to increase the iteration limit by
    104     calling .localsolve(..., iteration_limit=NEWLIMIT).""" % len(self.gps))
--> 105             gp = self.gp(x0, verbosity=verbosity-1)
    106             self.gps.append(gp)  # NOTE: SIDE EFFECTS
    107             try:

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/signomial_program.pyc in gp(self, x0, verbosity)
    133     def gp(self, x0=None, verbosity=1):
    134         """Get a GP approximation of this SP at x0"""
--> 135         gpconstr = self.as_gpconstr(x0)
    136         return GeometricProgram(self.cost, gpconstr,
    137                                 self.substitutions, verbosity=verbosity)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    181 
    182         When x0 is none, may return a default guess."""
--> 183         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    184         return ConstraintSet(gpconstrs,
    185                              self.substitutions, recursesubs=False)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    181 
    182         When x0 is none, may return a default guess."""
--> 183         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    184         return ConstraintSet(gpconstrs,
    185                              self.substitutions, recursesubs=False)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    181 
    182         When x0 is none, may return a default guess."""
--> 183         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    184         return ConstraintSet(gpconstrs,
    185                              self.substitutions, recursesubs=False)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    181 
    182         When x0 is none, may return a default guess."""
--> 183         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    184         return ConstraintSet(gpconstrs,
    185                              self.substitutions, recursesubs=False)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    181 
    182         When x0 is none, may return a default guess."""
--> 183         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    184         return ConstraintSet(gpconstrs,
    185                              self.substitutions, recursesubs=False)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in as_gpconstr(self, x0)
    688         x0.update({var: 1 for var in negy.varlocs if var not in x0})
    689         x0.update(self.substitutions)
--> 690         pc = PosynomialInequality(posy, "<=", negy.mono_lower_bound(x0))
    691         pc.substitutions = self.substitutions
    692         return pc

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in mono_lower_bound(self, x0)
    370         Monomial
    371         """
--> 372         return self.mono_approximation(x0)
    373 
    374 

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in mono_approximation(self, x0)
    420     def mono_approximation(self, x0):
    421         raise TypeError("Monomial approximation of %s is unnecessary - "
--> 422                         "it's already a Monomial." % str(self))
    423 
    424 

TypeError: Monomial approximation of 39.5*AR**2*C_{L_{aw}}**-2 is unnecessary - it's already a Monomial.
```

**Comment by pgkirsch** [comment] 2016-05-11 04:54
And yes, sorry, I _always_ forget about that trick to access a model's variables.

With option number two, I still need to reincorporate that constraint back into the model somehow (e.g. concatenation) right?

**Comment by bqpd** [comment] 2016-05-11 05:15
Naw, option 2 modifies the constraint in place.

(that substitution appears to be bugging out, hmm...)

**Comment by pgkirsch** [comment] 2016-05-11 05:17
Oh right sorry I wasn't reading it properly. I did that, but strangely my model is giving the same answer...hmmmmm ....

**Comment by pgkirsch** [comment] 2016-05-11 05:17
Oh, now that constraint is just super slack. Not what I expected to happen.

**Comment by pgkirsch** [comment] 2016-05-11 05:20
And also different from what happens when I manually edit the constraint.

**Comment by bqpd** [comment] 2016-05-11 05:23
hrrm.

**Comment by whoburg** [comment] 2016-06-15 17:00
could the unexpected behavior here possibly be due to #735?

**Comment by bqpd** [comment] 2016-06-16 01:56
Possibly, but generally I've seen hash misses cause bad results tables, not modeling errors.

**Comment by bqpd** [comment] 2016-06-19 02:54
@pgkirsch, do you have the code you did for option 2 above so I can try and reproduce it?

**Comment by bqpd** [comment] 2016-06-19 03:16
(fixed option 1, that works now)

**Comment by pgkirsch** [comment] 2016-06-19 04:22
Sorry, I don't think so. I believe I was just doing it in an interactive python session.

**Comment by pgkirsch** [comment] 2016-06-19 04:23
(with the gpkitmodels.aircraft.wing model)

**Comment by bqpd** [comment] 2016-06-19 04:26
ah, no worries. I'll close this issue then now that option 1 works?

**Closed by bqpd** 2016-06-19 04:26 UTC
Labels: question

**Comment by pgkirsch** [comment] 2016-06-19 04:38
Sounds good, thanks!
