### ISSUE TITLE
Sweeps pass a vectorized solution to process_solution

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#913] opened 2016-09-27 00:47 UTC
@bqpd, I'm getting this error when trying to run sweeps:

``` python
/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/nomials/substitution.pyc in substitution(nomial, substitutions)
    146                 #                          " '%s' into '%s' of units '%s'." %
    147                 #                          (sub, var, var.units.units))
--> 148                 if sub != 0:
    149                     mag(cs_)[i] *= sub**x
    150                 elif x > 0:  # HACK to prevent RuntimeWarnings

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by bqpd** [comment] 2016-09-27 14:07
Any and all sweeps, or one in particular?

**Comment by mjburton11** [comment] 2016-09-27 14:18
Any and all sweeps are getting the problem.  If you run the make file in `1682master`, this error will come up when it gets to the sweep.  I tried running: 

```python
M.cost = M["MTOW"]
M.substitutions.update({"t_{loiter}": 6})
M.substitutions.update({"w_{lim}": ("sweep", np.linspace(0.05, 0.5, 15))})
sol = M.solve("mosek", skipsweepfailures=True)
```
And that didn't work either.

**Comment by bqpd** [comment] 2016-09-27 15:24
Ah, it's a problem in TightConstraintSet

**Comment by bqpd** [comment] 2016-09-27 15:26
As can be seen in the error message, it occurs during solution processing in TightConstraintSet.

**Comment by bqpd** [comment] 2016-09-27 15:27
The issue is that process_solution is now run after all sweeps, instead of after each sweep...

**Comment by mjburton11** [comment] 2016-09-27 15:29
Gotcha.

**Comment by bqpd** [comment] 2016-09-27 15:35
But now that we give unit-ed results to process_solution it would be a bit slow to to process results for every sweep...

**Comment by mjburton11** [comment] 2016-09-27 15:38
Yeah... that's too bad.  But I think we definitely need it to process after every sweep right?

**Comment by bqpd** [comment] 2016-09-27 15:44
I don't know about that. We should definitely do it individually for every sweep, but do we have to do it after every sweep?

**Comment by mjburton11** [comment] 2016-09-27 15:46
You mean we should do it for every value in the sweep, but not after the sweep has finished?

**Comment by bqpd** [comment] 2016-09-27 15:50
Not _until_ after the sweep has finished.

**Comment by mjburton11** [comment] 2016-09-27 15:51
Right.  Ok got it.  We are on the same page. Sorry for my confusing messages.

**Comment by bqpd** [comment] 2016-10-06 19:17
@mjburton11, could you check this is fixed by #920?

**Comment by whoburg** [comment] 2016-12-03 16:30
@mjburton11, is this still slowing you down?

**Comment by bqpd** [comment] 2016-12-03 18:34
@whoburg As we no longer use process_solution, this is not an issue on the current master.

**Comment by bqpd** [comment] 2016-12-29 20:59
Duplicate of #911

**Closed by bqpd** 2016-12-29 20:59 UTC
Labels: bug
