### ISSUE TITLE
linking within nested models

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#899] opened 2016-09-14 12:59 UTC
@bqpd: this is what we were talking about yesterday. 

I have a `Mission` model which creates 5 `FlightSegment` models.  Each `FlightSegment` has an `Engine` model.  The engine weight should be the same across the whole mission.  When I link it however, the weight shows up as `W_Mission, GasMALE`, instead of `W_Engine, Mission, GasMALE`.

**Comment by bqpd** [comment] 2016-11-30 18:34
As we no longer recommend linking, I'll close this issue (since linking was working as intended, see the reference issue above).

**Closed by bqpd** 2016-11-30 18:34 UTC
Labels: design discussion

**Comment by whoburg** [comment] 2016-12-02 17:51
This says to see #896 and that says to see this...

"Did you mean recursion?"

**Comment by bqpd** [comment] 2016-12-02 17:54
Haha, bad reference in this one.

**Comment by bqpd** [comment] 2016-12-02 18:04
This is part of a general discussion on how linking should work between submodels, which are no longer relevant.
