### ISSUE TITLE
Erroneous `each c must be positive` error

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#592] opened 2016-03-17 23:47 UTC
A model with no signomials gives an `each c must be positive` error. (The error goes away and the problem solves if you uncomment the AR substitution.)

```python
from gpkit import Variable, Model, SignomialsEnabled, units
from gpkit.constraints.tight import TightConstraintSet as TCS
from numpy import pi

alpha = Variable('\\alpha', '-')
ARh  = Variable('AR_h', '-')
amax = Variable('\\alpha_{max}', '-')
eta  = Variable('\\eta', '-')
CLah = Variable('C_{L_{ah}}', '-')
CLh  = Variable('C_{L_h}', '-')
CLw  = Variable('C_{L_w}', '-')
cma  = Variable('\\bar{c}', 'm')
Cmac = Variable('C_{m_{ac}}', '-')
lh   = Variable('l_h', 'm')
lfuse= Variable('l_{fuse}', 'm')
Sh   = Variable('S_h', 'm^2')
Sw   = Variable('S_w', 'm^2')
xCG  = Variable('x_{CG}', 'm')
xw   = Variable('x_w', 'm')
W    = Variable('W', 'N')


objective = W

constraints = [
               # Stability


               # Trim
               CLh*Sh*lh/(Sw*cma) >= Cmac + CLw*xw/cma,

               TCS([xCG + lh <= lfuse]),

               # DATCOM formula (TODO: add sweep, Mach)
               TCS([ (2*pi*ARh/CLah)**2 >= (ARh/eta)**2 + 8*pi*ARh/CLah]),
               CLh == CLah*alpha,
               alpha <= 0.1, # Angle of attack limited by stall (degrees)

               W >= 100*Sh*units.Pa
              ]

substitutions = {
                 '\\alpha_{max}': 0.1, # (0.1 radians = 6 deg)
                 #'AR_h': 4,
                 '\\eta': 0.97,
                 'C_{m_{ac}}': 0.1,
                 'C_{L_w}': 0.5,
                 '\\bar{c}': 5,
                 'l_{fuse}': 40,
                 'S_w': 125,
                 'x_{CG}': 20,
                 'x_w': 2,
                }

m = Model(objective, constraints, substitutions)

m.solve()
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/models/aircraft/htail.py in <module>()
     55 m = Model(objective, constraints, substitutions)
     56 
---> 57 m.solve()

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity-1)
---> 80             result = solvefn(solver, verbosity-1, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/geometric_program.pyc in solve(self, solver, verbosity, *args, **kwargs)
    190                 (solvername, solver_out.get("status", None)))
    191 
--> 192         result = self._compile_result(solver_out)
    193 
    194         self.result = result  # NOTE: SIDE EFFECTS

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/geometric_program.pyc in _compile_result(self, solver_out)
    291         for constraint in self.constraints:
    292             if hasattr(constraint, "process_result"):
--> 293                 constraint.process_result(result)
    294 
    295         return result

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/set.pyc in process_result(self, result)
    210         for constraint in self:
    211             if hasattr(constraint, "process_result"):
--> 212                 p = constraint.process_result(result)
    213                 if p:
    214                     processed.update(p)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/tight.pyc in process_result(self, result)
     20                 leftsubbed = constraint.left.sub(variables)
     21                 rightsubbed = constraint.right.sub(variables)
---> 22                 rel_diff = abs(1-(leftsubbed/rightsubbed).value)
     23                 if rel_diff >= self.reltol:
     24                     raise ValueError("Tightness requirement not met"

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in __div__(self, other)
    280             return Signomial(self.exps, self.cs/other)
    281         elif isinstance(other, Monomial):
--> 282             return other.__rdiv__(self)
    283         elif isinstance(other, NomialArray):
    284             return np.array(self)/other

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in __rdiv__(self, other)
    369         "Divide other by this Monomial"
    370         if isinstance(other, Numbers + (Signomial,)):
--> 371             return other * self**-1
    372         else:
    373             return NotImplemented

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in __pow__(self, other)
    379     def __pow__(self, other):
    380         if isinstance(other, Numbers):
--> 381             return Monomial(self.exp*other, self.c**other)
    382         else:
    383             return NotImplemented

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, exps, cs, require_positive, simplify, **descr)
    109             from .. import SIGNOMIALS_ENABLED
    110             if require_positive and not SIGNOMIALS_ENABLED:
--> 111                 raise ValueError("each c must be positive.")
    112             self.__class__ = Signomial
    113         else:

ValueError: each c must be positive.
```

**Comment by bqpd** [comment] 2016-03-25 04:50
Solves fine with cvxopt.

**Comment by bqpd** [comment] 2016-03-25 04:53
Oh. So the problem is that AR_h is unbounded above and wants to push to infinity.

**Comment by bqpd** [comment] 2016-03-25 04:57
Original issue closed by #605

**Comment by whoburg** [comment] 2016-03-25 14:54
I claim the root issue is not that `leftsubbed` and `rightsubbed` were left as monomials, but rather that they are both `inf`, because `AR_h` is unbounded above.

@pgkirsch, what behavior would you want from `TightConstraintSet` here? I'm advocating for showing the user the solve failure before we do any tightness checking -- which would have avoided this issue.

**Comment by pgkirsch** [comment] 2016-03-25 15:45
Sounds good to me.

**Closed** 2016-04-06 19:35 UTC
Labels: waiting on PR
