### ISSUE TITLE
No documentation on linking models

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#732] opened 2016-06-08 20:42 UTC
currently no documentation regarding linking models

**Comment by whoburg** [comment] 2016-06-08 21:04
Is this a duplicate of #672 and/or #537 ?

**Comment by mayork** [comment] 2016-06-08 21:06
similar, but what I meant was on the read the docs page I don't see anywhere that linking models is discussed...seems it might be good to add that under advanced commands

**Comment by whoburg** [comment] 2016-06-08 21:17
yep agreed; we ought to be able to fix #672 and #537 in the process of fixing this.

**Comment by mayork** [comment] 2016-06-08 23:45
if you want, I'll keep creating these issues when I find advanced commands without documentation, then once I think I understand them I can go back and draft up some documentation you and ned can review/edit later

**Comment by whoburg** [comment] 2016-06-09 04:35
that would be excellent.

**Comment by mayork** [comment] 2016-07-05 20:57
@whoburg what's the process for editing the documentation? I'm guessing it involves https://github.com/hoburg/gpkit/tree/master/docs/source  but I don't really know what to do...

**Comment by bqpd** [comment] 2016-07-05 21:12
Yup! If you look at the `.rst` files in there, you'll see they're formatted in the fairly readable "Rich Structured Text` format. Linking should presumably go in `advancedcommands.rst`

**Comment by mayork** [comment] 2016-07-05 21:13
okay great! looks pretty easy to do!

**Comment by bqpd** [comment] 2016-12-02 04:41
No longer relevant, with performance modeling.

**Closed by bqpd** 2016-12-02 04:41 UTC
