### ISSUE TITLE
KeyError on _compile_result

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1058] opened 2017-02-16 01:26 UTC
```python
In [5]: sol = m.solve()
Using solver 'cvxopt'
Solving for 24 variables.
Solving took 0.532 seconds.
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-5-5d57c2b01a74> in <module>()
----> 1 sol = m.solve()

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/prog_factories.py in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     82         else:
     83             self.program, solvefn = genfunction(self, verbosity)
---> 84             result = solvefn(solver, verbosity, *args, **kwargs)
     85             solution.append(result)
     86         solution.program = self.program

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.py in solve(self, solver, verbosity, warn_on_check, *args, **kwargs)
    182                 "A result dict can be generated via "
    183                 "program._compile_result(program.solver_out)." %
--> 184                 (solvername, solver_out.get("status", None)))
    185 
    186         self._generate_nula(solver_out)

RuntimeWarning: final status of solver 'cvxopt' was 'unknown', not 'optimal'.

The solver's result is stored in model.program.solver_out. A result dict can be generated via program._compile_result(program.solver_out).

In [6]: m.program._compile_result(m.program.solver_out)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-bf726454ca3b> in <module>()
----> 1 m.program._compile_result(m.program.solver_out)

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.py in _compile_result(self, solver_out)
    248         """
    249         primal = solver_out["primal"]
--> 250         nu, la = solver_out["nu"], solver_out["la"]
    251         # confirm lengths before calling zip
    252         assert len(self.varlocs) == len(primal)

KeyError: 'nu'
```

**Comment by bqpd** [comment] 2017-02-16 05:13
What's your cvxopt version?

**Comment by pgkirsch** [comment] 2017-02-16 05:48
1.1.8

On Feb 15, 2017, at 21:13, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


What's your cvxopt version?

**Comment by bqpd** [comment] 2017-02-16 05:49
Hmm, try upgrading...

**Comment by pgkirsch** [comment] 2017-02-16 18:58
Upgraded to 1.1.9 and still getting the same error

**Comment by bqpd** [comment] 2017-02-28 17:16
What do you get when you run `m.program._generate_nula(m.program.solver_out)` ? (also what is `m.program.solver_out`?)

**Comment by bqpd** [comment] 2017-03-06 16:50
ping @pgkirsch

**Comment by pgkirsch** [comment] 2017-03-07 21:40
Sorry for the slow response @bqpd.

```python
In [3]: m.program._generate_nula(m.program.solver_out)
/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.py:212: RuntimeWarning: invalid value encountered in divide
  for p_i, m_is in enumerate(m_iss)])

In [4]: m.program.solver_out
Out[4]: 
{'la': array([  1.00000000e+00,   1.00000000e+00,   2.52244777e-01,
          1.53086500e-01,   1.50759777e-01,   1.96464690e-01,
          1.73799496e-01,   2.69197666e-01,   2.10473568e-01,
          4.18668060e-01,   2.12804695e-01,   2.58902188e-05,
          7.46042311e-01,   3.69593265e-02,   3.69593163e-02,
          1.85455881e+00,   2.05738835e+00,   1.78821115e+00,
          2.14046905e+00,   2.01034694e-15,   5.00000837e-01,
          1.90582795e+00,   1.99855684e+00,   1.90584504e+00,
          1.99857318e+00,   2.11628864e+00,   1.59805712e+00,
          2.17393315e+00,   1.56297056e+00,   2.17392539e+00,
          1.56296271e+00,   1.38854515e+00,   1.07745057e+00,
          2.33630797e+00]),
 'nu': array([             nan,   3.49533050e-02,   9.06576200e-02,
          1.45485224e-01,   7.54440235e-02,   2.97668382e-01,
          7.39727910e-02,   8.85539821e-02,   5.48250329e-02,
          1.38439639e-01,   1.79406599e-01,   0.00000000e+00,
          7.28381784e-02,   1.53086500e-01,   1.50759777e-01,
          1.96464690e-01,   1.73799496e-01,   2.69197666e-01,
          2.10473568e-01,   4.18668060e-01,   2.12804695e-01,
          2.58902188e-05,   5.91324362e-01,   1.54717949e-01,
          3.69593265e-02,   3.69593163e-02,   1.85455881e+00,
          2.05738835e+00,   1.78821115e+00,   2.14046905e+00,
                     nan,   3.30735223e-03,   3.73580985e-02,
          3.73580985e-02,   0.00000000e+00,   4.21977288e-01,
          1.90582795e+00,   1.99855684e+00,   1.90584504e+00,
          1.99857318e+00,   2.11628864e+00,   1.59805712e+00,
          2.17393315e+00,   1.56297056e+00,   2.17392539e+00,
          1.56296271e+00,   1.38854515e+00,   1.07745057e+00,
          2.33630797e+00]),
 'primal': array([  6.00634080e+00,  -6.70839470e+04,   4.48597844e+00,
          4.78552888e+00,  -6.70837962e+04,  -6.70779472e+04,
          7.25296605e+00,  -6.70801276e+04,   4.98892154e+00,
         -1.34155505e+05,   4.69949378e+00,  -6.70831425e+04,
          5.41226596e+00,   6.11740901e+00,  -6.70836029e+04,
          5.46190608e+00,   4.80522252e+00,  -6.70849100e+04,
         -6.70544577e+04,   4.96544388e+00,  -6.70829883e+04,
         -1.34155392e+05,   4.03584458e+00,  -4.65459896e-01,
          6.17781160e+00]),
 'status': 'unknown'}
```

**Comment by bqpd** [comment] 2017-06-27 00:15
Closing, could not reproduce

**Closed by bqpd** 2017-06-27 00:15 UTC
