### ISSUE TITLE
unsupported operand type(s) for /: 'Monomial' and 'Signomial' with a united value

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#886] opened 2016-09-10 14:52 UTC
I had an issue with the constraint `htoc >= dhftClimb2 + 10000*units('ft')`. When I had it in a non SignomialsEnabled enviorment I got this error

```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.pyc in __init__(self, exps, cs, require_positive, simplify, **descr)
    111             from .. import SIGNOMIALS_ENABLED
    112             if require_positive and not SIGNOMIALS_ENABLED:
--> 113                 raise ValueError("each c must be positive.")
    114             self.__class__ = Signomial
    115         else:

ValueError: each c must be positive.
```

and when it was in SignomialsEnabled I got this error

```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.pyc in _gen_unsubbed(self)
    604     def _gen_unsubbed(self):
    605         "Returns the unsubstituted posys <= 1."
--> 606         l_lt_r, r_lt_l = self.left/self.right, self.right/self.left
    607         if l_lt_r.units:
    608             try:

TypeError: unsupported operand type(s) for /: 'Monomial' and 'Signomial'
```

However, by replacing 10000*units('ft') with a variable equal whose value is equal to 10000 feet, I was able to aleviate these issues (the new constraint is `htoc <= dhftClimb2 + alt10k`). I don't think this should be happening, thoughts?

The code is at https://github.com/hoburg/gpkit-models/pull/73/commits/daa1ac9c347e23e233b020e527cbba7fcfcebc28

**Comment by bqpd** [comment] 2016-09-23 18:27
This one's pretty obnoxious.

Long story short, pint 0.7.2 seems to be doing two function calls when a Quantity interacts with a NomialArray; one to convert the entry, the second to wrap the array inside a Quantity. We don't want that second one, and so I tried raising an error to see where that code was in pint so we could subvert it too, but it silently eats the error. :-/

**Comment by bqpd** [comment] 2016-11-30 18:29
Fixed by #953

**Comment by whoburg** [comment] 2016-12-04 02:57
@mayork, I'm trying to write a unit test for this, but I'm having trouble reproducing it (I'm trying back at commit 7706db90a6ebaad021374aeb2bb8cd8779fc8ffd)

Here's what I'm trying -- am I missing something you had in the original example?


```python
from gpkit import Variable, Model, units, SignomialsEnabled


htoc = Variable("h_{toc}", 30000, "ft", "top of climb")
dh2 = Variable("dh_2", "ft", "second segment climb")
with SignomialsEnabled():
    c = (htoc <= dh2 + 10000*units("ft"))
```

**Comment by whoburg** [comment] 2016-12-04 02:57
reopening in hopes that we can unit test it

**Comment by bqpd** [comment] 2016-12-04 03:08
I wrote a test for this already, I believe...

**Comment by bqpd** [comment] 2016-12-04 03:09
This was fixed by the pint subversion, I link to the wrong PR above.

**Closed** 2016-12-04 03:19 UTC
Labels: bug
