### ISSUE TITLE
Linking by a variable that is fixed in one constituent model

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#552] opened 2016-03-07 18:02 UTC
It appears as though if two models are linked by a variable `T` and `T` is a fixed variable in one of the models, but not in the other, the composed model ignores the fixed value and allows `T` to be free.

**Comment by bqpd** [comment] 2016-03-07 20:04
Yup, this is expected behaviour.

**Comment by pgkirsch** [comment] 2016-03-07 20:10
Can it not be?

**Comment by bqpd** [comment] 2016-03-07 20:12
Sure! Sorry, I thought there'd been a discussion about this already.

**Comment by pgkirsch** [comment] 2016-03-07 20:12
Use case: I have a model that is importing an atmosphere model. One of my atmosphere models (`tropopause`) has a constant temperature, so it needs to be fixed in the parent model too. I could have a constraint `T == 216*units.K` (as I do for now) but that seems inelegant.

**Comment by bqpd** [comment] 2016-03-07 20:13
You could also just sub `{T: 216}` into the composed model.

**Comment by pgkirsch** [comment] 2016-03-07 20:13
There may well have been, sorry if I'm forgetting about it. I think previously we weren't aware of examples where it would be useful to go this way.

**Comment by pgkirsch** [comment] 2016-03-07 20:14
I suppose I could but that doesn't seem ideal because tropopause should always have  `T = 216` so needing to substitute in whenever I use it doesn't seem like it conveys the right kind of intent.

**Comment by bqpd** [comment] 2016-03-07 20:17
So the problem is `m = atmosphere_model1 & atmosphere_model2` where one has a fixed T?

I think that  `m = atm1 & atm2; m.substitutions.update({atm2["T"]: atm2.substitutions["T"]})` is nicely unambiguous, but still annoying.

**Comment by bqpd** [comment] 2016-03-07 20:18
The problem is what to do in this case as well as the case where two models both have a substitution but disagree on its value; ignoring all linked substitutions at least has a nice consistency.

**Comment by pgkirsch** [comment] 2016-03-07 20:18
Nah it's `aircraft_model & atmosphere_model` where the atmosphere model could be `troposphere` or `tropopause`. The former has a free `T`, the latter has a fixed `T`.

**Comment by bqpd** [comment] 2016-03-07 20:19
(wondering: Why is `T` in `aircraft_model`? not that it's relevant)

**Comment by pgkirsch** [comment] 2016-03-07 20:19
For speed of sound --> Mach number

**Comment by pgkirsch** [comment] 2016-03-07 20:20
You're right about the consistency. Perhaps this change could go in the upcoming refactor where linking is more explicit?

**Comment by bqpd** [comment] 2016-03-07 20:22
(nifty!)

That could work. Also we can just default to prioritizing substitutions over free variables and raise an error if values disagree.

**Comment by pgkirsch** [comment] 2016-03-07 20:25
My vote would be for no default, because it is so easy to overlook an accidentally linked variable.

**Comment by bqpd** [comment] 2016-03-07 20:28
Sorry, meant to say we that we can preserve substitutions instead of enforcing free variables.

**Comment by whoburg** [comment] 2016-03-07 21:57
good discussion.

documentation push: We're currently lacking even a basic overview of linked models on read the docs (unless I missed it), so I always feel a bit foggy on the assumptions and requirements for linking (e.g., do the vars need the same descr? ...) As a result, I sometimes don't use linking simply because I can't remember how to use it right.

... or does this documentation need to wait for the refactor because it will change so dramatically?

**Comment by bqpd** [comment] 2016-03-07 22:00
The refactor will open up a lot more freedom for arguments during linking, so it would be a good time to clarify what we want to be possible.

**Comment by bqpd** [comment] 2016-03-08 01:33
Try now? Should install 3.4.10

**Comment by whoburg** [comment] 2016-03-08 01:37
shucks, still get a `Could not load settings file.`

also, pip has version as 3.5.0:

```
whoburg$ pip install gpkit
Collecting gpkit
  Downloading gpkit-0.3.5.0.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 2.4MB/s
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/envs/vtest2/lib/python2.7/site-packages (from gpkit)
Requirement already satisfied (use --upgrade to upgrade): scipy in ./anaconda/envs/vtest2/lib/python2.7/site-packages (from gpkit)
Building wheels for collected packages: gpkit
  Running setup.py bdist_wheel for gpkit ... done
  Stored in directory: /Users/whoburg/Library/Caches/pip/wheels/8d/e2/d8/16b11de9d9cb8b89d1a4a6c03426b385008712892408917c0f
Successfully built gpkit
Installing collected packages: gpkit
Successfully installed gpkit-0.3.5.0
```

**Comment by bqpd** [comment] 2016-03-08 01:38
Oops. Try again now...

**Comment by bqpd** [comment] 2016-03-08 01:38
That was an accident that I'd hoped I'd ctrl-c'd in time.

**Comment by bqpd** [comment] 2016-03-08 01:44
Doesn't look like it's working on https://acdl.mit.edu/csi/job/gpkit_Install/28/

**Comment by whoburg** [comment] 2016-03-08 01:44
hmm, now I can't get it to show me the download bar even in a new virtualenv! and still the settings error.

**Comment by whoburg** [comment] 2016-03-08 01:44
```
whoburg$ pip install gpkit
Collecting gpkit
Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/whoburg/anaconda/envs/ggg/lib/python2.7/site-packages (from gpkit)
Requirement already satisfied (use --upgrade to upgrade): numpy in /Users/whoburg/anaconda/envs/ggg/lib/python2.7/site-packages (from gpkit)
Installing collected packages: gpkit
Successfully installed gpkit-0.3.5.0
```

**Comment by bqpd** [comment] 2016-03-08 01:46
It should be getting 0.3.5.1 by now...

**Comment by whoburg** [comment] 2016-03-08 01:46
let me try blasting away my pip cahce

**Comment by whoburg** [comment] 2016-03-08 01:50
oh boy. no more `Could not load settings file` error (woohoo), but the unit tests fail -- and what is `eburn` doing in my unittests printout!?

```
======================================================================
ERROR: test_trivial_sp (gpkit.tests.t_model.TestSP_mosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/tests/t_model.py", line 225, in test_trivial_sp
    sol = m.localsolve(verbosity=0, solver=self.solver)
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/model.py", line 385, in localsolve
    *args, **kwargs)
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/model.py", line 502, in _solve
    result = solvefn(*args, **kwargs)
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/signomial_program.py", line 120, in localsolve
    result = gp.solve(solver, verbosity-1, *args, **kwargs)
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/geometric_program.py", line 135, in solve
    solverfn, solvername = _get_solver(solver)
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/geometric_program.py", line 126, in _get_solver
    from ._mosek import expopt
  File "/Users/whoburg/anaconda/envs/vtest/lib/python2.7/site-packages/gpkit/_mosek/expopt.py", line 22, in <module>
    raise ImportError("Could not load MOSEK library: "+repr(e))
ImportError: Could not load MOSEK library: ImportError('/home/eburn/.gpkit/expopt.so not found.',)
```

**Comment by bqpd** [comment] 2016-03-08 01:52
whaaaat

**Comment by bqpd** [comment] 2016-03-08 01:53
Yup, it did. As did the settings file, which explains why you weren't getting that error anymore.

**Comment by bqpd** [comment] 2016-03-08 01:54
`import setuptools` brings in everything. :-1:

**Comment by whoburg** [comment] 2016-03-08 02:20
should we revert the push to PyPI then?

**Comment by bqpd** [comment] 2016-03-08 05:36
It's no worse, and has other updates.

**Comment by bqpd** [comment] 2016-03-15 18:15
This issue is a mess, closing. @pgkirsch, for our original discussion see #563

**Closed by bqpd** 2016-03-15 18:15 UTC
Labels: design discussion
