### ISSUE TITLE
Problem with extracting performance equations that link subsystems

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#955] opened 2016-11-24 17:05 UTC
Oops sorry, clicking enter posted this issue. Preparing a detailed description.

**Comment by 1ozturkbe** [comment] 2016-11-24 17:17
This concerns hoburg/d8, and has to do with trying to remove the fuselage attribute from the VT_simple_profile init, and moving the equations that use self.fuse references into the overarching D8() and D8P() classes. 

You can see a demo of the issue in commits 1968db, and be4397. There is only one difference between the two commits. 
 
For the commit 1968db, the equations of interest:
```python
self.fuse['l_{fuse}'] >= self.vt['\\Delta x_{lead_v}'] + self.fuseP['x_{CG}'],
self.vt['x_{CG_{vt}}'] >= self.fuseP['x_{CG}']+(self.vt['\\Delta x_{lead_v}']+self.vt['\\Delta x_{trail_v}'])/2,
```
are in VT_simple_profile.py, which has a fuse attribute. 

For commit be4397, these equations have been moved into D8P class, which is the D8 performance model:

```python
self.aircraft.fuse['l_{fuse}'] >= self.aircraft.VT.vtns['\\Delta x_{lead_v}'] + self.fuseP['x_{CG}'],
self.aircraft.VT.vtns['x_{CG_{vt}}'] >= self.fuseP['x_{CG}']+(self.aircraft.VT.vtns['\\Delta x_{lead_v}']+self.aircraft.VT.vtns['\\Delta x_{trail_v}'])/2,
```
For 1968db, the commit d8.py converges to a solution that satisfies all constraints. Once we move the equations into the D8P class however, the code starts throwing bounding errors for the variables in the equations, and throws UNKNOWN. This is real odd. Any attempts to bound all variables using BCS (included in the last few lines) throws the following error:

```python
TypeError: 'NoneType' object has no attribute '__getitem__'
```
an issue within process_result. 

Does anyone have ideas? I am going to be afk for a while, but will try to be in touch about resolving this error this evening. Have a good Thanksgiving!

**Comment by bqpd** [comment] 2016-11-30 18:25
@1ozturkbe and I could not reproduce this issue in person, so closing for now.

**Closed by bqpd** 2016-11-30 18:25 UTC
