### ISSUE TITLE
TightConstraintSet.process_result not being called with SignomialsEnabled

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#593] opened 2016-03-18 14:59 UTC
The first constraint in the model below is slack, but it doesn't trigger an error. In fact `TCS.process_result()` doesn't seem to get called at all.

```python
from gpkit import Variable, Model, SignomialsEnabled, units
from gpkit.constraints.tight import TightConstraintSet as TCS
from numpy import pi, tan

alpha = Variable('\\alpha', '-')
ARh  = Variable('AR_h', '-')
amax = Variable('\\alpha_{max}', '-')
eta  = Variable('\\eta', '-')
CLah = Variable('C_{L_{ah}}', '-')
CLaw = Variable('C_{L_{aw}}', '-')
CLh  = Variable('C_{L_h}', '-')
CLw  = Variable('C_{L_w}', '-')
cma  = Variable('\\bar{c}', 'm')
Cmac = Variable('C_{m_{ac}}', '-')
lh   = Variable('l_h', 'm')
lfuse= Variable('l_{fuse}', 'm')
Sh   = Variable('S_h', 'm^2')
Sw   = Variable('S_w', 'm^2')
SM   = Variable('S.M.', '-')
SMmin= Variable('S.M._{min}', '-')
tanLh= Variable('\\tan(\\Lambda_h)', '-')
xCG  = Variable('x_{CG}', 'm')
xw   = Variable('x_w', 'm')
W    = Variable('W', 'N')


objective = W

with SignomialsEnabled():
    constraints = [
                   # Stability
                   TCS([SM + xw/cma >= CLah*Sh*lh/(CLaw*Sw*cma)]),
                   SM >= SMmin,

                   # Trim
                   CLh*Sh*lh/(Sw*cma) >= Cmac + CLw*xw/cma,

                   TCS([xCG + lh <= lfuse]),

                   # DATCOM formula (Mach number makes it SP)
                   TCS([(ARh/eta)**2 * (1 + tanLh**2) + 8*pi*ARh/CLah
                        <= (2*pi*ARh/CLah)**2]),
                   CLh == CLah*alpha,
                   alpha <= amax,

                   W >= 100*Sh*units.Pa
                  ]

substitutions = {
                 '\\alpha_{max}': 0.1, # (6 deg)
                 'AR_h': 4,
                 '\\eta': 0.97,
                 'C_{m_{ac}}': 0.1,
                 'C_{L_{aw}}': 2*pi,
                 'C_{L_w}': 0.5,
                 '\\bar{c}': 5,
                 'l_{fuse}': 40,
                 'S_w': 125,
                 'S.M._{min}': 0.05,
                 '\\tan(\\Lambda_h)': tan(30*pi/180),
                 'x_{CG}': 20,
                 'x_w': 2,
                }

m = Model(objective, constraints, substitutions)

m.localsolve()
```

**Comment by pgkirsch** [comment] 2016-03-18 15:03
`TCS.process_result()` is called fine when you remove `SignomialsEnabled()` and the signomial constraint.

**Comment by bqpd** [comment] 2016-03-18 15:09
Oh, I think I see what's going on.

**Comment by pgkirsch** [comment] 2016-03-18 15:47
Because `process_result` only gets called on the monomial approximation of an SP constraint?

**Comment by bqpd** [comment] 2016-03-18 16:00
Not quite! The problem is that as_gpconstr of a tight constraint does not
return a tight constraint

**Comment by bqpd** [comment] 2016-03-18 16:01
Try

```python
def as_gpconstr(self, x0):
    gpconstr = super(TightConstraint, self).as_gpconstr(x0)
    return TightConstraint([gpconstr])  # the [] may be unncessary
```

**Comment by pgkirsch** [comment] 2016-03-18 21:25
That helps (without `[]`), but strangely the SP constraint is actually passing the tightness check, despite not being tight. Well the GP approximation is tight but not the original SP.

**Comment by bqpd** [comment] 2016-03-19 00:27
Yeah I realized the plane that the better way to solve this is actually not
to add that method but just to run process_result in signomialprogram as
well as geometricprogram

**Comment by pgkirsch** [comment] 2016-03-19 15:55
Wouldn't it be more appropriate to put these checks in `check_solution` instead of `process_result`?

**Comment by bqpd** [comment] 2016-03-19 16:04
ConstraintSets aren't called during check solution, and check solution is
only in Geometric Program

**Comment by bqpd** [comment] 2016-03-25 04:14
This has been fixed by 2afe34d, I believe?

**Comment by whoburg** [comment] 2016-03-25 19:03
... but that isn't merged yet

**Comment by whoburg** [comment] 2016-03-25 19:43
now it is

**Closed by whoburg** 2016-03-25 19:43 UTC
Labels: waiting on PR
