### ISSUE TITLE
Signomial Equality Constraints for arrays

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#756] opened 2016-07-04 13:31 UTC
I think there might be a problem with the signomial equality constraint when used with vector variables. I have code that runs fine, but if I use a signomial equality constraint with vector variables where I previously had an inequality I get this error. The code is at https://github.com/hoburg/gpkit-models/pull/73/commits/86484e30c24f4080e721825f5eb33871ed6a8409.

```
Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\Commercial Sizing\Commerical_Flight_Profile.py", line 444, in <module>
    m = CommercialAircraft()
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\Commercial Sizing\Commerical_Flight_Profile.py", line 382, in __init__
    atm = Atmosphere(Nseg)
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\Commercial Sizing\atmosphere.py", line 56, in __init__
    (hu)**0.00022+ 0.000248 * (hu)**8.7e-05+ 1.41e-15 * (hu)**2.88 + 5.66e-08 * (hu)**1.06)),
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 724, in __init__
    SignomialInequality.__init__(self, left, "<=", right)
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 654, in __init__
    ScalarSingleEquationConstraint.__init__(self, left, oper, right)
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 435, in __init__
    self).__init__(Signomial(left), oper, Signomial(right))
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 73, in __init__
    assert len(cs) == len(exps)
TypeError: object of type 'int' has no len()
```

**Comment by mayork** [comment] 2016-07-05 18:56
If looking into this could be a high priority issue I'd appreciate it. Having trouble getting the atmosphere model to work right, but I think it could be a very good place to use a signomial equality

**Comment by bqpd** [comment] 2016-07-05 21:22
The problem is that `SignomialEqualityConstraint(array, array)` is not currently supported. For now, use

```python
array_sec = [SignomialEqualityConstraint(a1[i], a2[i]) for i in range(len(a1))]
```

**Comment by mayork** [comment] 2016-07-05 21:26
easy fix, thanks!

**Comment by mayork** [comment] 2016-09-09 15:10
@1ozturkbe

**Comment by bqpd** [comment] 2016-11-19 06:52
Fixed in #941

**Comment by whoburg** [comment] 2016-11-19 07:06
is it unit tested?

**Comment by bqpd** [comment] 2016-11-19 07:08
Not for arrays, yet!

**Comment by bqpd** [comment] 2016-11-29 21:02
It is now unit tested!

**Closed by bqpd** 2016-11-29 21:02 UTC
Labels: waiting on PR
